[package]
name = "magrslib"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
nalgebra = "0.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vtkio = "0.6"

[dev-dependencies]
approx = "0.5"
